# Generated by Django 5.1.1 on 2024-10-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(blank=True),
        ),
    ]
