# Generated by Django 5.1.1 on 2024-10-10 18:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_user_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="patp",
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.PositiveIntegerField(
                help_text="Azimuth point",
                primary_key=True,
                serialize=False,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(4294967295),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                editable=False,
                help_text="Pronounceable version of the Urbit ID",
                max_length=14,
                unique=True,
            ),
        ),
    ]
