# Generated by Django 5.1.1 on 2024-10-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_post_url_post_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="link",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
